name: gpt3_webview
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.3.2
  device_info: ^2.0.3
  flutter_user_agentx: ^1.2.4
  easy_loading: ^0.0.4
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19

flutter:

  uses-material-design: true

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/brain.png"
flutter_native_splash:
    color: "#000000"
    image: "assets/images/brain.png"
    android: true
    ios: true